<?php

namespace App\Http\Controllers;
use App\Models\Category;
use App\Models\Sub_category;
use App\Models\Tag;
use App\Models\Admin_post;
use App\Models\Post_Category;

use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class Admin_PostController extends Controller {

    public function index() {
        $data = Admin_post::query()->get();
        return view( 'admin-post.admin-post', compact( 'data' ) );
    }

    public function add() {
        // $categories = Category::all();
        // $categories = Category::with( 'subcategories' )->get();

        // return view( 'admin-post.AddAdminPost', compact( 'categories' ) );
        return view( 'admin-post.AddAdminPost' );
    }

    public function store( Request $request ) 
        {
            $request->validate( [
                'title'=>'required',
                // 'insitution' => 'required',
                // 'post_name' => 'required',
                // 'eligibility'=>'required',
                // 'place'=>'required',
                // 'salary'=>'required',
                // 'last_date'=>'required',
                // 'website' => 'required',
                'post_content' => 'required',
                // 'post_image' => 'required',
                // 'status'=>'required',

            ], [
                // 'name.required' => 'Name cannot be empty',
                // 'title.required' => 'The title cannot be empty.',
                // 'post_content.required' => 'The post content is required.',
            ] );
            $selectedCategories = $request->input( 'categories', [] );
            $selectedSubcategories = $request->input( 'subcategories', [] );

            if ( $request->hasFile( 'post_image' ) ) {
                $file = $request->file( 'post_image' );
                $filename = time() . '_' . $file->getClientOriginalName();
                // Append original filename
                $file->move( 'post-image/', $filename );
                //  $imagepath = $request->file( 'image' )->store( 'uploads' );
                //if want store in  storage file then this function
            }
            // if ( $request->hasFile( 'post_image' ) ) {
            //     $file = $request->file( 'post_image' );

            //     // Store the file in a designated path, e.g., 'Post-images'
            //     $path = $file->storeAs( 'Post-images', time() . '_' . $file->getClientOriginalName(), 'public' );

            //     // If you don't need to store details in the database, you can simply provide the path for further use
            //     $url = Storage::url($path);
            
            //     // You can use $url to display or link to the uploaded image directly
            // }
            $userId=Auth::user()->id;
            
            $data = new Admin_post;
            $data->post_title = $request->title ?? '';
            $data->insitution_name = $request->insitution ?? '';
            $data->post_name = $request->post_name ?? '';
            $data->eligibility = $request->eligibility ?? '';
            $data->place = $request->place ?? '';
            $data->salary = $request->salary ?? 0;
            $data->last_date = $request->last_date ?? '';
            $data->website = $request->website ?? '';
            $data->post_content = $request->post_content;
            //$data->post_image = $request->post_image;
            $data->post_image = $filename ?? '';

            // $data->category_id = json_encode($selectedCategories);
            // $data->sub_category_id = json_encode($selectedSubcategories);
            
            $data->admin_user_id = $userId;
            $data->status=$request->status ?? '0';
            $data->save();

            
            // After saving, you can get the ID and store it in the post_id field
            $postId = $data->id; // This is the primary key generated by the save() method
            // $data->id = $postId; // Assuming you have a post_id field in your Admin_post model

            // Save again to persist the post_id
            $data->save();
            
                // Store selected categories
                // foreach ($selectedCategories as $categoryId) 
                // {
                //     $data=Category::findorfail($categoryId);

                //         Post_Category::create([
                //         'category_id' => $categoryId,
                //         'sub_category_id'=>0,
                //         'slug'=>$data->slug_category,
                //         'admin_post_id' => $postId,
                //         'admin_user_id'=>$userId,
                //         'status'=>$request->status??'0',
                        
                //     ]);
                // }

                // Store selected subcategories
                // foreach ($selectedSubcategories as $subcategoryId) 
                // {
                //     $data=Sub_category::findorfail($subcategoryId);

                //         Post_Category::create([
                //         'sub_category_id' => $subcategoryId,
                //         'category_id'=>0,
                //         'slug'=>$data->slug_subcategory,
                //         'admin_post_id' => $postId,
                //         'admin_user_id'=>$userId,
                //         'status'=>$request->status??'0',
                //     ]);
                // }
            

            return redirect('admin-post');
        }

    public function show(Request $request,$id)
        {
                // $id = $request->id;
                $data = Admin_post::find($id);
                // $categories = Category::with('subcategories')->get();
                // $postCategory = Post_Category::where('admin_post_id',$id) ->get();
                // return view('admin-post.EditAdminPost',compact('data','categories','postCategory'));
                return view('admin-post.EditAdminPost',compact('data'));
                // return response()->json(['data' => $data]);
        }

        public function update(Request $request)
            {
                $id = $request->id;
            
                // $file = $request->file('post_image');
                // $filename = time() . '_' . $file->getClientOriginalName(); // Append original filename
                // $file->move('post-image/', $filename);
                //  $imagepath= $request->file('image')->store('uploads'); //if want store in  storage file then this function
                
                if ($request->hasFile('post_image')) {
                
                    // Retrieve the uploaded file
                    $file = $request->file('post_image');
            
                    // Generate a unique filename
                    $filename = time() . '_' . $file->getClientOriginalName();
            
                    // Move the new file to the specified location
                    $file->move('post-image/', $filename);
                }
                $data = Admin_post::find($id);
                // if ($request->hasFile('post_image')) {
                //     // echo 'kkkk';
                //     // die;
                //     // Retrieve the uploaded file
                //     $file = $request->file('post_image');
                
                //     // Generate a unique filename
                //     $filename = time() . '_' . $file->getClientOriginalName();
                
                //     // Move the new file to the specified location
                //     $file->move('post-image/', $filename);
                
                //     // Optionally, delete the old file if necessary
                //     if ($item->post_image) {
                //         Storage::delete('post-image/' . $item->post_image);
                //     }
                
                //     // Update the post_image field with the new filename
                //     $update['post_image'] = $filename;  // Set the new filename here
                // } else {
                //     // If no new file was uploaded, keep the existing filename
                //     $update['post_image'] = $item->post_image; // Retain the existing filename
                // }
                // $userId=Auth::user()->id;
            
                $update = [
                    'post_title'=>$request->title,
                    'insitution_name' => $request->insitution ?? '',
                    'post_name' => $request->post_name ?? '',
                    'eligibility' => $request->eligibility ?? '',
                    'place' => $request->place ?? '',
                    'salary' => $request->salary ?? 0,
                    'last_date' => $request->last_date ?? '',
                    'website' => $request->website ?? '',
                    'post_content' =>$request->post_content,
                    'post_image' => $filename ?? $data->post_image ?? '',
                    // 'admin_user_id'=>$userId,
                    'status'=>$request->status,
                ];
                // print_r($update);
                // die;

                // $data = Admin_post::find($id);
                $data->update($update);
                $data->save();
                
                
                
                // Step 1: Delete all existing category relationships for the given admin_post_id
                // Post_Category::where('admin_post_id', $id)->delete();
                // // Step 2: Add new category relationships
                // if ($request->has('categories')) {
                //     foreach ($request->input('categories') as $categoryId) {
                //         $data=Category::findorfail($categoryId);

                //         Post_Category::create([
                //             'admin_post_id' => $id,
                //             'category_id' => $categoryId,
                //             'sub_category_id' => 0, // or handle this based on your logic
                //             'slug'=>$data->slug_category,
                //             'admin_user_id' => auth()->id(), // or set this based on your logic
                //             'status' => $request->status, // Set status as needed
                //         ]);
                //     }
                // }
            
                // Step 3: If you have subcategories to handle separately
                // if ($request->has('subcategories')) {
                //     foreach ($request->input('subcategories') as $subcategoryId) {
                //         $data=Sub_category::findorfail($subcategoryId);
                    
                //         Post_Category::create([
                //             'admin_post_id' => $id,
                //             'category_id' => 0, // or handle this based on your logic
                //             'sub_category_id' => $subcategoryId,
                //             'slug'=>$data->slug_subcategory,
                //             'admin_user_id' => auth()->id(), // or set this based on your logic
                //             'status' => $request->status, // Set status as needed
                //         ]);
                //     }
                // }
                return redirect('admin-post');;
            }
        
        public function destroy(Request $request,$id)
            {
                // $id = $request->id;
                $data = Admin_post::find($id);
                $data->delete();
                
                return redirect('admin-post');
                // return response()->json(['data' => $data ] );
            }

}
