<?php

namespace App\Http\Controllers;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Auth;

use App\Models\Creative_house_category;
use App\Models\Creative_house_item;
use App\Models\Author_template;
use App\Models\Book_call;

use Illuminate\Http\Request;

class Creative_house_itemController extends Controller {

    public function index() {
        $categorydata = Creative_house_category::query()->get();
        $data = Creative_house_item::query()->with('category')->get();
        // print_r( $data );
        // die;
        return view( 'creative_house.creative_house_item.creative_house_item', compact( 'data','categorydata') );
    }

    public function getData(Request $request)
    {
        if ($request->ajax()) {

            $sortColumnIndex = $request->get('order')[0]['column']; // value depend on datatable field not in table
            // echo 'working';
            // echo $sortColumnIndex;
           
            $sortDirection = $request->get('order')[0]['dir'];
    
            // Map column index to actual column names (you can adjust this as per your columns)
            // $columns = [
            //     'id','creative_house_category_id ','author_template_id ','book_call_template_id','creative_house_thumbnail','creative_house_video_url','creative_house_video_title','requirement_title','requirement_description','display_order','status'
            // ]; // value depend on datatable field not in table
    
            $columns = [
                'id','creative_house_category_id ','creative_house_thumbnail','creative_house_video_title','display_order','status'
            ];
            // Get the column name for sorting
            $sortColumn = $columns[$sortColumnIndex];// value depend on datatable field not in table
            
            // echo 'working';
            // echo $sortColumnIndex;
            // echo $sortColumn;
            // die;

            // Apply the sorting to the query
            // $data = Creative_house_item::select('*')->with('category')->orderBy($sortColumn, $sortDirection);

            // Start building the query, including the relation 'category'
            $query = Creative_house_item::select('creative_house_item.*', 'creative_house_category.creative_house_category_name','creative_house_category.status as category_status')
            ->join('creative_house_category', 'creative_house_item.creative_house_category_id', '=', 'creative_house_category.id') // Correct table name used here
            ->orderBy($sortColumn, $sortDirection);

                // To see the SQL query generated by the query builder:
            // $sqlQuery = $query->toSql();
            // dd($sqlQuery); // This will dump the SQL query

            // // To get the data and see the result (you can also dd() this to inspect the data):
            // $data = $query->get();
            // dd($data);

              // If you are searching, include the search in the query
            if ($request->has('search') && $request->get('search')['value'] != '') {
                $search = $request->get('search')['value'];

                $query->where(function($q) use ($search) {
                    $q->where('creative_house_item.id', 'LIKE', "%$search%")
                    ->orWhere('creative_house_item.creative_house_video_title', 'LIKE', "%$search%")
                    ->orWhere('creative_house_category.creative_house_category_name', 'LIKE', "%$search%") // Corrected to match the correct table
                    ->orWhere('creative_house_item.display_order', 'LIKE', "%$search%")
                    ->orWhere('creative_house_item.status', 'LIKE', "%$search%");
                });
            }

            $data = $query->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('status', function ($row) {
                    if ($row->status == 0) {
                        return '<span class="badge bg-danger">Inactive</span>';
                    } else {
                        return '<span class="badge bg-success">Active</span>';
                    }
                })
                ->addColumn('creative_house_category_name', function ($row) {
                    return $row->category->creative_house_category_name ? $row->category->creative_house_category_name : 'N/A';
                })
                // ->addColumn('creative_house_thumbnail', function ($row) {
                //     $imgUrl = $row->creative_house_thumbnail ?? '';
                //     return '<img src="' . $imgUrl . '" alt="Image" width="70" height="70">';
                // })
                ->addColumn('creative_house_thumbnail', function ($row) {
                    $imgPath = $row->creative_house_thumbnail ?? '';
                    $baseUrl = env('AWS_URL'); // Get the base URL from the .env file
                    $imgUrl = $baseUrl . '/' . $imgPath; // Concatenate the base URL with the stored path
                    return '<img src="' . $imgUrl . '" alt="No Image Available" width="70" height="70">';
                })
                ->editColumn('creative_house_video_url', function ($row) {
                    return '<a href="'. $row->creative_house_video_url. '" target="_blank">Click</a>';
                })
                // ->editColumn('created_at', function ($row) {
                //     return \Carbon\Carbon::parse($row->created_at)->format('d/m/Y');
                // })
                // ->editColumn('updated_at', function ($row) {
                //     return \Carbon\Carbon::parse($row->updated_at)->format('d/m/Y');
                // })
                ->addColumn('action', function ($row) {
                    $previewButton = '';
                    // if ($row->status == 1 && $row->category_status == 1) {
                    //     $previewButton = '<a href="https://d1r5jv57b9z1uu.cloudfront.net/" target="_blank" class="mb-1 btn btn-info btn-sm mr-2">
                    //             <i class="fas fa-eye"></i>
                    //         </a>';
                    // }
                    if ($row->status == 1 && $row->category->status == 1) {
                        $previewButton = '<a href="https://d1r5jv57b9z1uu.cloudfront.net/Single-Video/' . $row->id . '" target="_blank" class="mb-1 btn btn-info btn-sm mr-2">
                                <i class="fas fa-eye"></i>
                            </a>';
                    }
                    
                    return '
                        <div class="d-flex">
                            <a href="' . route('creative-house-item.show', $row->id) . '" class="mb-1 btn btn-primary btn-sm mr-2">
                                <i class="fas fa-edit"></i>
                            </a>
                            '.$previewButton.'
                            <a href="#" class="mb-1 btn btn-danger btn-sm" onclick="confirmDelete(\'' . route('creative-house-item.destroy', $row->id) . '\');">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    ';
                })
                ->addColumn('navigate', function ($row) {
                    $approachCount = $row->creative_house_approach()->count();
                    $finalOutputCount = $row->creative_house_final_output()->count();

                    return '
                        <div class="d-flex flex-column">
                            <a href="' . route('creative-house-approach.index',['item_id' => $row->id]) . '" class="mb-1 btn btn-primary btn-sm text-nowrap">
                                Creative Approach( ' . $approachCount . ' )
                            </a>
                             <a href="' . route('creative-house-final-output.index',['item_id' => $row->id]) . '" class="mb-1 btn btn-primary btn-sm text-nowrap">
                                Creative Final Output( ' . $finalOutputCount . ' )
                            </a>
                          
                        </div>
                    ';
                })
                ->rawColumns(['creative_house_category_name','status','action','creative_house_thumbnail','creative_house_video_url','navigate'])
                ->make(true);
        }
    }

    public function add() {
        $categorydata = Creative_house_category::query()->get();
        $authordata = Author_template::query()->get();
        $bookcalldata = Book_call::query()->get();

        return view( 'creative_house.creative_house_item.add_creative_house_item',compact('categorydata','authordata','bookcalldata'));
    }

    public function store( Request $request )  {

        // print_r( $request->creative_house_video_url );
        // die;
        $request->validate( [
            // 'title'=>'required',

        ], [
            // 'name.required' => 'Name cannot be empty',

        ] );

        $image = upload_file_to_s3($request, 'creative_house_thumbnail', 'creative-house-thumbnail');
        $video = upload_file_to_s3($request, 'creative_house_upload_video_url', 'creative-house-video');
        $requirement_image = upload_file_to_s3($request, 'requirement_title', 'creative-house-requirement-logo');

        // if ( $request->hasFile( 'creative_house_thumbnail' ) ) {
        //     $file = $request->file( 'creative_house_thumbnail' );
        //     $filename = time() . '_' . $file->getClientOriginalName();
        //     // Append original filename
        //     $file->move( 'creative-house-thumbnail/', $filename );
        //     //  $imagepath = $request->file( 'image' )->store( 'uploads' );
        //     //if want store in  storage file then this function
        // }

        $userId = Auth::user()->id;

        $data = new Creative_house_item;
        $data->creative_house_category_id = $request->creative_house_category_id??0;
        $data->author_template_id = $request->author_template_id??0;
        $data->book_call_template_id = $request->book_call_template_id??0;
        $data->creative_house_thumbnail = $image ?? '';
        $data->creative_house_upload_video_url = $video ?? '';
        $data->creative_house_video_url = $request->creative_house_video_url ?? '';
        $data->creative_house_video_title = $request->creative_house_video_title ?? '';
        $data->requirement_title = $requirement_image ?? '';
        $data->requirement_description = $request->requirement_description ?? '';
        $data->creative_house_year = $request->creative_house_year;
        // $data->creative_house_display_at_home = $request->display_at_home ?? 0;
        $data->display_order = $request->display_order ?? 0;
        $data->user_id = $userId;
        $data->status = $request->status ?? 0;
        $data->save();

        return redirect()->route('creative-house-item.index');
        // return redirect( 'creative/creative_house/creative_house_item' );
    }

    public function show( Request $request, $id ) {
        // $id = $request->id;
        $categorydata = Creative_house_category::query()->get();
        $authordata = Author_template::query()->get();
        $bookcalldata = Book_call::query()->get();
        $data = Creative_house_item::find($id);
        // print_r( $data->toArray() );
        // die;
        return view( 'creative_house.creative_house_item.edit_creative_house_item', compact( 'data','categorydata','authordata','bookcalldata' ) );
    }

    public function update( Request $request ) {
        $id = $request->id;
        // print_r($request->creative_house_upload_video_url);
        // print_r($request->existing_video);
        // die;

        // $file = $request->file( 'post_image' );
        // $filename = time() . '_' . $file->getClientOriginalName();
        // Append original filename
        // $file->move( 'post-image/', $filename );
        //  $imagepath = $request->file( 'image' )->store( 'uploads' );
        //if want store in  storage file then this function

        $image = upload_file_to_s3($request, 'creative_house_thumbnail', 'creative-house-thumbnail');
        $requirement_image = upload_file_to_s3($request, 'requirement_title', 'creative-house-requirement-logo');


             // Initialize the video variable
             $video = null;

             // Check if the user uploaded a new video
            if ($request->hasFile('creative_house_upload_video_url')) {
                // Upload the new video and store it
                $video = upload_file_to_s3($request, 'creative_house_upload_video_url', 'creative-house-video');
            } elseif ($request->has('existing_video') && $request->existing_video) {
                // If no new video is uploaded, use the existing video from the hidden input
                $video = $request->existing_video;
            } else {
                // If the user has removed the video (no video uploaded, and no existing video)
                $video = '';  // This will remove the old video
            }


        $data = Creative_house_item::find( $id );

        $userId = Auth::user()->id;

        $update = [

            'creative_house_category_id' => $request->creative_house_category_id,
            'author_template_id'=>$request->author_template_id,
            'book_call_template_id'=>$request->book_call_template_id,
            'creative_house_thumbnail' => $image ??$data->creative_house_thumbnail ?? '',
            'creative_house_upload_video_url' => $video,
            'creative_house_video_url' => $request->creative_house_video_url ?? '',
            'creative_house_video_title' => $request->creative_house_video_title?? '',
            'requirement_title' => $requirement_image ?? $data->requirement_title ??'',
            'requirement_description' => $request->requirement_description ?? '',
            'creative_house_year' => $request->creative_house_year ,
            'display_order' => $request->display_order ?? 0,
            // 'creative_house_display_at_home'=>$request->display_at_home ?? 0,
            'user_id' => $userId,
            'status'=> $request->status ?? 0,

        ];
        // print_r( $update );
        // die;

        // $data = Admin_post::find( $id );
        $data->update( $update );
        // $data->save();

        return redirect()->route('creative-house-item.index');
        // return redirect( 'creative/creative_house/creative_house_item' );
    }

    public function destroy( Request $request, $id ) {

        $data = Creative_house_item::find( $id );
        $data->delete();

        return redirect()->route('creative-house-item.index');
        // return redirect( 'creative/creative_house/creative_house_item' );
    }

}
